package model.business.control;

import java.sql.SQLException;

import communication.IConnectionLog;


/**
 * Class that receives the messages generated by the server and stored it into the database.
 */
public class DBLogManager implements IConnectionLog {

	public DBLogManager() {
	}
	
	// Métodos del log del servidor
	
	public void putMessage(String messageType, String message) throws SQLException {
//		EntradaLog entrada;
//		
//		entrada = new EntradaLog(null, tipoMensaje, mensaje);
//		FPEntradaLog.insertar(entrada);
	}
	
	public void putMessage(String user, String messageType, String message) throws SQLException {
//		EntradaLog entrada;
//		
//		entrada = new EntradaLog(usuario, tipoMensaje, mensaje);
//		FPEntradaLog.insertar(entrada);
	}

	@Override
	public void updateConnectedClients(int n) {
		// These messages are not stored in the database		
	}

}
